name: fakestore
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  google_fonts: 6.1.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  dio: ^5.4.1
  logger: ^2.2.0
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.7
  injectable: ^2.3.5
  fpdart: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_native_splash: 2.3.10
  bloc_test: ^9.1.7
  extended_image: ^8.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  background_image: assets/images/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 20
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/svg/
    - assets/images/
    - assets/env/
    - assets/icon/
  uses-material-design: true
